name: Boost test

on:
  workflow_dispatch:

env: 
  CX_TENANT: ${{ vars.BOOST_CX_TENANT }}
  CX_APIKEY: ${{ secrets.BOOST_CX_APIKEY }}

jobs:
  configureuid:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
  Scan: 
    runs-on: ubuntu-latest
    needs: configureuid
    container:
      image: m1splacedsoul/chmrx_boost
      options: --user ${{ needs.configureuid.outputs.uid_gid }} 
    steps:
      - name: (0) Stage source code
        uses: actions/checkout@v3
        with:
          path: 'src'
      
      - name: (1) Validate login
        run: | 
          /home/runner/bin/cx auth validate
          
      - name: (2) Run scan
        run: |
          /home/runner/bin/scan_phase_driver.sh -r ${{ github.event.repository.name }} 
      - name: (3) Acquire scan results
        run: |
          /home/runner/bin/scan_results.sh -r ${{ github.event.repository.name }} src /home/runner/output
          cat /home/runner/output/native_output.json.sarif >> sarif.json
