name: NightVision Native, Standalone

on:
  push:
  workflow_dispatch:
  
permissions:
  security-events: write

env:
  NIGHTVISION_TOKEN: ${{ secrets.NIGHTVISION_TOKEN }}
  NIGHTVISION_TARGET: https://localhost:9000/
  
jobs:
  build-code:
    uses: aedify-prototype-organization/javaspringvulny/.github/workflows/docker-image.yml@v1
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Spawn JavaSpringVulny daemon
        run: docker-compose up -d; sleep 10
