name: NightVision Native, Standalone

on:
  push:
  workflow_dispatch:

jobs:

  stage-code:

    runs-on: ubuntu-latest

    steps:
    - uses: (0) actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build

    - name: (1) run docker image
      run: docker-compose up -d; sleep 10
  
  stage-nightvision:
    runs-on: ubuntu-latest

    steps:
    - name: (2) Install NightVision
      run: |
          wget -c https://downloads.nightvision.net/binaries/latest/nightvision_latest_linux_amd64.tar.gz -O - | tar -xz; sudo mv nightvision /usr/local/bin/
                  python -m pip install semgrep --user

  
  
