on:
  workflow_dispatch:

jobs:
  configureuid:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
  Report: 
    runs-on: ubuntu-latest
    needs: configureuid
    container:
      image: m1splacedsoul/chmrx_boost
    steps:
      - name: Report
        run: |
          echo ${{ needs.configuruid.outputs.uid_gid }}
